
# plyr is recommended to be loaded before dplyr for better performance
library(plyr)

library(bnma)
library(BUGSnet)
library(combinat)
library(cookies)
library(cowplot)
library(data.table)
library(data.tree)
library(dplyr)
library(DT)
library(future)
library(jsonlite)
library(knitr)
library(gemtc)
library(ggiraphExtra)
library(ggplot2)
library(ggpubr)
library(ggrepel)
library(glue)
library(lubridate)
library(magick)
library(matrixcalc)
library(MCMCvis)
library(meta)
library(metafor)
library(mvtnorm)
library(netmeta)
library(patchwork)
library(plotly)
library(plotrix)
library(promises)
library(R.utils)
library(R6)
library(remotes)
library(rio)
library(rmarkdown)
library(shiny)
library(shinyAce)
library(shinyalert)
library(shinyBS)
library(shinycssloaders)
library(shinydashboard)
library(shinyjs)
library(shinyWidgets)
library(stringr)
library(tidyr)

#To install BUGSnet, run this line
# remotes::install_github("audrey-b/BUGSnet@v1.1.2", upgrade = TRUE, build_vignettes = TRUE, dependencies = TRUE)
