install.packages("remotes")
remotes::install_github("audrey-b/BUGSnet")


install.packages("data.table")
install.packages("dplyr")
install.packages("gemtc")
install.packages("ggplot2")
install.packages("knitr")
install.packages("metafor")
install.packages("netmeta")
install.packages("plotly")
install.packages("plyr")
install.packages("rmarkdown")
install.packages("shiny") 
install.packages("shinyAce")
install.packages("shinyalert")
install.packages("shinyBS")
install.packages("shinydashboard")
install.packages("shinyjs")
install.packages("shinyWidgets")

