common_class <- R6::R6Class(
  classname = "common",
  public = list(
   data = NULL,
   upgraded_data = NULL,
   wrangled_data = NULL,
   is_data_valid = NULL,
   is_data_uploaded = NULL,
   outcome = NULL,
   ranking_option = NULL,
   treatment_df = NULL,
   outcome_measure = NULL,
   reference_treatment_all = NULL,
   reference_treatment_sub = NULL,
   disconnected_indices = NULL,
   main_connected_data = NULL,
   non_covariate_data_all = NULL,
   model_type = NULL,
   excluded_studies = NULL,
   subsetted_data = NULL,
   subsetted_treatment_df = NULL,
   bugsnet_all = NULL,
   bugsnet_sub = NULL,
   freq_all = NULL,
   freq_sub = NULL,
   bayes_all = NULL,
   bayes_sub = NULL,
   bayes_rank_all = NULL,
   bayes_rank_sub = NULL,
   nodesplit_all = NULL,
   nodesplit_sub = NULL,
   bayes_deviance_all = NULL,
   bayes_deviance_sub = NULL,
   bayes_mcmc_all = NULL,
   bayes_mcmc_sub = NULL,
   download_format = NULL,
   meta = NULL,
   tasks = NULL,
   logger = NULL,
   state = NULL,
   reset = function(){
     self$data <- NULL
     self$upgraded_data <- NULL
     self$wrangled_data <- NULL
     self$valid_data <- NULL
     self$is_data_uploaded <- NULL
     self$outcome <- NULL
     self$ranking_outcome <- NULL
     self$treatment_df <- NULL
     self$outcome_measure <- NULL
     self$reference_treatment_all <- NULL
     self$reference_treatment_sub <- NULL
     self$disconnected_indices <- NULL
     self$main_connected_data <- NULL
     self$non_covariate_data_all <- NULL
     self$model_type <- NULL
     self$excluded_studies <- NULL
     self$subsetted_data <- NULL
     self$subsetted_treatment_df <- NULL
     self$bugsnet_all <- NULL
     self$bugsnet_sub <- NULL
     self$freq_all <- NULL
     self$freq_sub <- NULL
     self$bayes_all <- NULL
     self$bayes_sub <- NULL
     self$bayes_rank_all <- NULL
     self$bayes_rank_sub <- NULL
     self$nodesplit_all <- NULL
     self$nodesplit_sub <- NULL
     self$bayes_deviance_all <- NULL
     self$bayes_deviance_sub <- NULL
     self$bayes_mcmc_all <- NULL
     self$bayes_mcmc_sub <- NULL
     self$meta <- NULL
     self$state <- NULL
     invisible(self)
   }
  )
)

