test_that("rep_markdown produces a renderable .Rmd when no analysis has been conducted", {
  app <- shinytest2::AppDriver$new(app_dir = system.file("shiny", package = "metainsight"), name = "e2e_setup_load")
  app$set_inputs(tabs = "rep")
  app$set_inputs(repSel = "rep_markdown")
  sess_file <- app$get_download("rep_markdown-dlRMD")
  expect_false(is.null(sess_file))
  lines <- readLines(sess_file)
  writeLines(lines, sess_file)
  rmarkdown::render(sess_file)
  html_file <- gsub("Rmd","html", sess_file)
  expect_gt(file.info(html_file)$size, 1000)
  app$stop()
})

test_that("rep_markdown produces a renderable .Rmd file after an analysis", {
  app <- shinytest2::AppDriver$new(app_dir = system.file("shiny", package = "metainsight"), name = "e2e_setup_load")
  app$set_inputs(tabs = "setup")
  app$set_inputs(setupSel = "setup_load")
  app$click("setup_load-run")
  app$set_inputs(setupSel = "setup_define")
  app$click("setup_define-run")
  app$set_inputs(tabs = "summary")
  app$set_inputs("summary_exclude-exclusions" = c("Study01", "Study25"))
  app$set_inputs(summarySel = "summary_char")
  app$set_inputs(main = "Results")
  app$set_inputs(summarySel = "summary_study")
  app$set_inputs(summarySel = "summary_network")
  app$set_inputs(tabs = "rep")
  app$set_inputs(repSel = "rep_markdown")
  sess_file <- app$get_download("rep_markdown-dlRMD")
  expect_false(is.null(sess_file))
  lines <- readLines(sess_file)
  chunks <- sum(grepl("```\\{r", lines))
  expect_equal(chunks, 8) # 1 intro, 6 modules, one with 2 chunks
  rmarkdown::render(sess_file)
  html_file <- gsub("Rmd", "html", sess_file)
  expect_gt(file.info(html_file)$size, 100000)
  app$stop()
})
