```{asis, echo = {{bayes_model_knit}}, eval = {{bayes_model_knit}}, include = {{bayes_model_knit}}}
### Fit the Bayesian models
```

```{r, echo = {{bayes_model_knit}}, include = {{bayes_model_knit}}}
bayes_model_all <- bayes_model(main_connected_data, treatment_df, outcome, outcome_measure, model_type, reference_treatment_all)
bayes_model_sub <- bayes_model(connected_data_sub, treatment_df_sub, outcome, outcome_measure, model_type, reference_treatment_sub)
```

```{r, echo = {{bayes_model_knit}}, include = {{bayes_model_knit}}}
bayes_model_all$dic |>
  gt::gt(rownames_to_stub = TRUE) |>
  gt::tab_header(title = "Model fit for all studies") |>
  gt::tab_options(column_labels.hidden = TRUE) |>
  gt::fmt_number(rows = c(1:3), decimals = 3) |>
  gt::fmt_number(rows = 4, decimals = 0)
```
```{r, echo = {{bayes_model_knit}}, include = {{bayes_model_knit}}}
bayes_model_sub$dic |>
  gt::gt(rownames_to_stub = TRUE) |>
  gt::tab_header(title = "Model fit with selected studies excluded") |>
  gt::tab_options(column_labels.hidden = TRUE) |>
  gt::fmt_number(rows = c(1:3), decimals = 3) |>
  gt::fmt_number(rows = 4, decimals = 0)
```
