```{asis, echo = {{bayes_ranking_knit}}, eval = {{bayes_ranking_knit}}, include = {{bayes_ranking_knit}}}
### Generate ranking plots
```

```{r, echo = {{bayes_ranking_knit}}, include = {{bayes_ranking_knit}}}
bayes_ranking_all <- bayes_ranking(main_connected_data, treatment_df, bayes_model_all, ranking_option)
bayes_ranking_sub <- bayes_ranking(connected_data_sub, treatment_df_sub, bayes_model_sub, ranking_option)
```

```{asis, echo = {{bayes_ranking_knit}}, eval = {{bayes_ranking_knit}}, include = {{bayes_ranking_knit}}}
#### For all studies
```

```{asis, echo = {{bayes_ranking_knit}}, eval = {{bayes_ranking_knit}}, include = {{bayes_ranking_knit}}}
{r, results = 'asis'}
```
```{r, echo = {{bayes_ranking_knit}}, include = {{bayes_ranking_knit}}}
bayes_ranking_forest_all <- bayes_forest(bayes_model_all, treatment_df, reference_treatment_all, "", TRUE)

htmltools::HTML(bayes_ranking_forest_all$svg)
```

```{r, echo = {{bayes_ranking_knit}}, include = {{bayes_ranking_knit}}}
if ({{bayes_ranking_rank_style}} == "radial"){
  radial_all <- RadialSUCRA(bayes_ranking_all, {{bayes_ranking_colourblind}})
  if (!{{bayes_ranking_simple}}){
    radial_all$Original
  } else {
    radial_all$Alternative
  }
} else {
  LitmusRankOGram(bayes_ranking_all, {{bayes_ranking_colourblind}})
}
```

```{r, echo = {{bayes_ranking_knit}}, include = {{bayes_ranking_knit}}}
knitr::kable(ranking_table(bayes_ranking_all), digits = 2)
```

```{asis, echo = {{bayes_ranking_knit}}, eval = {{bayes_ranking_knit}}, include = {{bayes_ranking_knit}}}
{r, results = 'asis'}
```
```{r, echo = {{bayes_ranking_knit}}, include = {{bayes_ranking_knit}}}
bayes_ranking_network_all <- summary_network(frequentist_all, bugsnet_all, {{bayes_ranking_network_style}})

htmltools::HTML(bayes_ranking_network_all$svg)
```

```{asis, echo = {{bayes_ranking_knit}}, eval = {{bayes_ranking_knit}}, include = {{bayes_ranking_knit}}}
#### Excluding selected studies
```

```{asis, echo = {{bayes_ranking_knit}}, eval = {{bayes_ranking_knit}}, include = {{bayes_ranking_knit}}}
{r, results = 'asis'}
```
```{r, echo = {{bayes_ranking_knit}}, include = {{bayes_ranking_knit}}}
bayes_ranking_forest_sub <- bayes_forest(bayes_model_sub, treatment_df_sub, reference_treatment_sub, "", TRUE)

htmltools::HTML(bayes_ranking_forest_sub$svg)
```

```{r, echo = {{bayes_ranking_knit}}, include = {{bayes_ranking_knit}}}
if ({{bayes_ranking_rank_style}} == "radial"){
  radial_sub <- RadialSUCRA(bayes_ranking_sub, {{bayes_ranking_colourblind}})
  if (!{{bayes_ranking_simple}}){
    radial_sub$Original
  } else {
    radial_sub$Alternative
  }
} else {
  LitmusRankOGram(bayes_ranking_sub, {{bayes_ranking_colourblind}})
}
```

```{r, echo = {{bayes_ranking_knit}}, include = {{bayes_ranking_knit}}}
knitr::kable(ranking_table(bayes_ranking_sub), digits = 2)
```

```{asis, echo = {{bayes_ranking_knit}}, eval = {{bayes_ranking_knit}}, include = {{bayes_ranking_knit}}}
{r, results = 'asis'}
```
```{r, echo = {{bayes_ranking_knit}}, include = {{bayes_ranking_knit}}}
bayes_ranking_network_sub <- summary_network(frequentist_sub, bugsnet_sub, {{bayes_ranking_network_style}})

htmltools::HTML(bayes_ranking_network_sub$svg)
```
