```{asis, echo = {{covariate_ranking_knit}}, eval = {{covariate_ranking_knit}}, include = {{covariate_ranking_knit}}}
### Generate ranking plots
```

```{r, echo = {{covariate_ranking_knit}}, include = {{covariate_ranking_knit}}}
covariate_ranking <- covariate_ranking(main_connected_data, treatment_df, covariate_model, ranking_option, covariate_value)
```

```{asis, echo = {{covariate_ranking_knit}}, eval = {{covariate_ranking_knit}}, include = {{covariate_ranking_knit}}}
{r, results = 'asis'}
```
```{r, echo = {{covariate_ranking_knit}}, include = {{covariate_ranking_knit}}}
covariate_forest(covariate_model, treatment_df, reference_treatment_all, ranking = TRUE)
```

```{asis, echo = {{covariate_ranking_knit}}, eval = {{covariate_ranking_knit}}, include = {{covariate_ranking_knit}}}
{r, results = 'asis'}
```
```{r, echo = {{covariate_ranking_knit}}, include = {{covariate_ranking_knit}}}
if ({{covariate_ranking_rank_style}} == "radial"){
  RadialSUCRA(covariate_ranking, !{{covariate_ranking_simple}}, {{covariate_ranking_colourblind}})
} else {
  LitmusRankOGram(covariate_ranking, {{covariate_ranking_colourblind}})
}
```

```{r, echo = {{covariate_ranking_knit}}, include = {{covariate_ranking_knit}}}
knitr::kable(ranking_table(covariate_ranking), digits = 2)
```

```{asis, echo = {{covariate_ranking_knit}}, eval = {{covariate_ranking_knit}}, include = {{covariate_ranking_knit}}}
{r, results = 'asis'}
```
```{r, echo = {{covariate_ranking_knit}}, include = {{covariate_ranking_knit}}}
summary_network(frequentist_all, bugsnet_all, {{covariate_ranking_network_style}})
```
